"""update models

Revision ID: 601895d24cdd
Revises: d2a3ac719b31
Create Date: 2026-02-01 14:09:57.985192

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "601895d24cdd"
down_revision: Union[str, Sequence[str], None] = "d2a3ac719b31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "wiating_for_promo_code",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "waiting_for_admin_password",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "waiting_for_admin_password")
    op.drop_column("user", "wiating_for_promo_code")
    # ### end Alembic commands ###
