"""update models

Revision ID: 9b41bbb63e29
Revises: 601895d24cdd
Create Date: 2026-02-01 14:36:53.397685

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9b41bbb63e29"
down_revision: Union[str, Sequence[str], None] = "601895d24cdd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "waiting_for_promo_code",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )
    op.drop_column("user", "wiating_for_promo_code")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "wiating_for_promo_code",
            sa.BOOLEAN(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    op.drop_column("user", "waiting_for_promo_code")
    # ### end Alembic commands ###
